version: '3'

vars:
  proj_name: hello-flutter3
  ContainerName: 'hello-flutter3'
  ImageName: mooxe/apt_flutter

includes:
  image:
    taskfile: ~/.taskfilehub/hubs/image.yml
    vars:
      ContainerName: '{{.ContainerName}}'
      ImageName: '{{.ImageName}}'

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  run-dev:
    cmds:
      - task: image:run:run-dev
        vars:
          run_option: '-v ~/.taskfilehub:/root/.taskfilehub'


  coder:
    cmds:
      # -e PASSWORD=netserver
      - podman run
          -ti --rm
          --name=code-server
          -p 8456:8456
          -v ~/.coder/config/extensions:/root/.local/share/code-server/extensions:Z
          -v ~/.local/share/fonts:/root/.local/share/fonts:Z
          -v ~/.gitconfig:/root/.gitconfig:Z
          -v ~/.local/bin/hx:/usr/local/bin/hx:Z
          -v $(pwd):/root/WorkSpace/{{.proj_name}}
          -v $(pwd)/.vscode:/root/WorkSpace/.vscode
            mooxe/apt_coder
